<?php
declare(strict_types = 1);

namespace Nelliel\Setup\Installer;

defined('NELLIEL_VERSION') or die('NOPE.AVI');

use Nelliel\Language\Translator;
use Nelliel\Render\RenderCoreSimple;
use Nelliel\Utility\FileHandler;

class CryptSetup
{
    private $file_handler;
    private $translator;
    private $render_core;

    function __construct(FileHandler $file_handler, Translator $translator)
    {
        $this->file_handler = $file_handler;
        $this->translator = $translator;
        $this->render_core = new RenderCoreSimple(NEL_INCLUDE_PATH . 'Setup/Installer/templates/');
    }

    public function setup(string $step)
    {
        if ($step === 'crypt-check') {
            if (file_exists(NEL_CONFIG_FILES_PATH . 'crypt.php')) {
                $this->output('crypt/crypt_found', ['page_title' => __('Hashing config already exists')]);
            } else {
                $this->output('crypt/crypt_ask', ['page_title' => __('Hashing config')]);
            }
        }

        if ($step === 'crypt-config') {
            if (isset($_POST['new_crypt_config'])) {
                $this->output('crypt/crypt_ask', ['page_title' => __('Hashing config')]);
            }

            if (isset($_POST['customize_crypt_config'])) {
                $this->output('crypt/crypt_config', ['page_title' => __('Hashing config')]);
            }

            if (!isset($_POST['keep_crypt_config'])) {
                $config = $this->cryptConfig();
                $this->writeCryptConfig($config);
            }
        }

        if ($step === 'crypt-config') {
            $this->output('crypt/crypt_config_complete', ['page_title' => __('Hashing config complete')]);
        }
    }

    private function cryptConfig(): array
    {
        $config = array();
        $config['account_password_algorithm'] = $_POST['account_password_algorithm'] ?? 'BCRYPT';
        $config['account_password_bcrypt_cost'] = intval($_POST['account_password_bcrypt_cost'] ?? 12);
        $config['account_password_argon2_memory_cost'] = intval($_POST['account_password_argon2_memory_cost'] ?? 1024);
        $config['account_password_argon2_time_cost'] = intval($_POST['account_password_argon2_time_cost'] ?? 2);
        $config['account_password_argon2_threads'] = intval($_POST['account_password_argon2_threads'] ?? 2);
        $config['account_password_max_length'] = intval($_POST['account_password_max_length'] ?? 256);
        $config['post_password_strong_hashing'] = boolval($_POST['post_password_strong_hashing'] ?? false);
        $config['post_password_strong_algorithm'] = $_POST['post_password_strong_algorithm'] ?? 'BCRYPT';
        $config['post_password_strong_bcrypt_cost'] = intval($_POST['post_password_strong_bcrypt_cost'] ?? 6);
        $config['post_password_max_length'] = intval($_POST['post_password_max_length'] ?? 256);
        $config['ip_strong_hashing'] = boolval($_POST['ip_strong_hashing'] ?? false);
        $config['ip_strong_algorithm'] = $_POST['ip_strong_algorithm'] ?? 'BCRYPT';
        $config['ip_strong_bcrypt_cost'] = intval($_POST['ip_strong_bcrypt_cost'] ?? 6);
        return $config;
    }

    private function writeCryptConfig(array $config, bool $overwrite = true): bool
    {
        if (!$overwrite && file_exists(NEL_CONFIG_FILES_PATH . 'crypt.php')) {
            return false;
        }

        $prepend = "\n" . '// Hashing config generated by Nelliel installer';
        $this->file_handler->writeInternalFile(NEL_CONFIG_FILES_PATH . 'crypt.php',
            $prepend . "\n" . nel_config_var_export($config, '$crypt_config'), true);
        return true;
    }

    private function output(string $template_file, array $render_data = array()): void
    {
        $render_data['base_stylesheet'] = NEL_STYLES_WEB_PATH . 'core/base_style.css';
        $html = $this->render_core->renderFromTemplateFile($template_file, $render_data);
        echo $this->translator->translateHTML($html);
        die();
    }
}